spring:
  datasource:  # Oracle dataSource 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@dblab_high?TNS_ADMIN=C:/Oracle/Wallet_DBLab    # use Oracle Wallet
#    url: jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=...))(connect_data=(service_name=...))(security=(ssl_server_dn_match=yes)))
    username: spring
    password: Framework2023   
#    hikari:   # HikariCP settings
#      minimumIdle: 5
#      maximumPoolSize: 20
#      idleTimeout: 30000
#      connectionTimeout: 30000
#      maxLifetime: 2000000
#      poolName: HikariPool          
  mvc:  
    view:     # JSP views
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    generate-ddl: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        # do not changes camel case to snake case, which is the default spring.jpa.hibernate.naming.implicit-strategy 
  devtools:
    livereload:
      enabled: true
      
mybatis:
  type-aliases-package: com.example.jpetstore.domain
#  mapper-locations: com/example/jpetstore/dao/mybatis/mapper/**/*.xml
  
logging:
  level:
    com:
      example:
        jpetstore:
          dao:
            mybatis:
              mapper: DEBUG           
    org:
        hibernate: INFO  
          
server:
  port: 8088
